package com.bnu.springdemo.entity;

// Generated Apr 19, 2014 6:58:41 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderProduct generated by hbm2java
 */
@Entity
@Table(name = "order_product", catalog = "sales")
public class OrderProduct implements java.io.Serializable {

	private OrderProductId id;
	private Product product;
	private SalesOrder salesOrder;
	private Integer qtyOrdered;
	private Double unitPrice;

	public OrderProduct() {
	}

	public OrderProduct(OrderProductId id, Product product,
			SalesOrder salesOrder) {
		this.id = id;
		this.product = product;
		this.salesOrder = salesOrder;
	}

	public OrderProduct(OrderProductId id, Product product,
			SalesOrder salesOrder, Integer qtyOrdered, Double unitPrice) {
		this.id = id;
		this.product = product;
		this.salesOrder = salesOrder;
		this.qtyOrdered = qtyOrdered;
		this.unitPrice = unitPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orderId", column = @Column(name = "order_id", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "product_id", nullable = false)) })
	public OrderProductId getId() {
		return this.id;
	}

	public void setId(OrderProductId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public SalesOrder getSalesOrder() {
		return this.salesOrder;
	}

	public void setSalesOrder(SalesOrder salesOrder) {
		this.salesOrder = salesOrder;
	}

	@Column(name = "qty_ordered")
	public Integer getQtyOrdered() {
		return this.qtyOrdered;
	}

	public void setQtyOrdered(Integer qtyOrdered) {
		this.qtyOrdered = qtyOrdered;
	}

	@Column(name = "unit_price", precision = 22, scale = 0)
	public Double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Double unitPrice) {
		this.unitPrice = unitPrice;
	}

}
