package com.bnu.springdemo.entity;

// Generated Apr 19, 2014 6:58:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "sales")
public class Product implements java.io.Serializable {

	private Long productId;
	private String name;
	private Integer qtyInHand;
	private String description;
	private Set<OrderProduct> orderProducts = new HashSet<OrderProduct>(0);

	public Product() {
	}

	public Product(String name, Integer qtyInHand, String description,
			Set<OrderProduct> orderProducts) {
		this.name = name;
		this.qtyInHand = qtyInHand;
		this.description = description;
		this.orderProducts = orderProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "product_id", unique = true, nullable = false)
	public Long getProductId() {
		return this.productId;
	}

	public void setProductId(Long productId) {
		this.productId = productId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "qty_in_hand")
	public Integer getQtyInHand() {
		return this.qtyInHand;
	}

	public void setQtyInHand(Integer qtyInHand) {
		this.qtyInHand = qtyInHand;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderProduct> getOrderProducts() {
		return this.orderProducts;
	}

	public void setOrderProducts(Set<OrderProduct> orderProducts) {
		this.orderProducts = orderProducts;
	}

}
