package com.bnu.springdemo.entity;

// Generated Apr 19, 2014 6:58:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SalesOrder generated by hbm2java
 */
@Entity
@Table(name = "sales_order", catalog = "sales")
public class SalesOrder implements java.io.Serializable {

	private Long orderId;
	private Customer customer;
	private Date orderDate;
	private Date orderTime;
	private Double amount;
	private Set<OrderProduct> orderProducts = new HashSet<OrderProduct>(0);

	public SalesOrder() {
	}

	public SalesOrder(Customer customer) {
		this.customer = customer;
	}

	public SalesOrder(Customer customer, Date orderDate, Date orderTime,
			Double amount, Set<OrderProduct> orderProducts) {
		this.customer = customer;
		this.orderDate = orderDate;
		this.orderTime = orderTime;
		this.amount = amount;
		this.orderProducts = orderProducts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_id", unique = true, nullable = false)
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "order_date", length = 10)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "order_time", length = 8)
	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "salesOrder")
	public Set<OrderProduct> getOrderProducts() {
		return this.orderProducts;
	}

	public void setOrderProducts(Set<OrderProduct> orderProducts) {
		this.orderProducts = orderProducts;
	}

}
